require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/flights", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Flight. As you add validations to Flight, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Flight.create! valid_attributes
      get flights_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      flight = Flight.create! valid_attributes
      get flight_url(flight)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_flight_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      flight = Flight.create! valid_attributes
      get edit_flight_url(flight)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Flight" do
        expect {
          post flights_url, params: { flight: valid_attributes }
        }.to change(Flight, :count).by(1)
      end

      it "redirects to the created flight" do
        post flights_url, params: { flight: valid_attributes }
        expect(response).to redirect_to(flight_url(Flight.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Flight" do
        expect {
          post flights_url, params: { flight: invalid_attributes }
        }.to change(Flight, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post flights_url, params: { flight: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested flight" do
        flight = Flight.create! valid_attributes
        patch flight_url(flight), params: { flight: new_attributes }
        flight.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the flight" do
        flight = Flight.create! valid_attributes
        patch flight_url(flight), params: { flight: new_attributes }
        flight.reload
        expect(response).to redirect_to(flight_url(flight))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        flight = Flight.create! valid_attributes
        patch flight_url(flight), params: { flight: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested flight" do
      flight = Flight.create! valid_attributes
      expect {
        delete flight_url(flight)
      }.to change(Flight, :count).by(-1)
    end

    it "redirects to the flights list" do
      flight = Flight.create! valid_attributes
      delete flight_url(flight)
      expect(response).to redirect_to(flights_url)
    end
  end
end
